# Generated by Django 2.1.4 on 2019-06-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
