# Generated by Django 2.1.4 on 2019-06-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user2',
        ),
    ]
