# Generated by Django 2.1.4 on 2019-06-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
