# Generated by Django 2.1.4 on 2019-06-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190629_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
